### PR TITLE
#general -> #intros for introduction

### PR DESCRIPTION
**Pull request by yukis4san**
Changed the channel's name from "general" to "intros" when people are suggested to write introductions.

### CODE REVIEW

**Comment by Joi** [comment]
Maybe also change #general to #intro in the English part? @yukis4san

**Comment by yukis4san** [comment]
I just edited the English parts and organised the doc. Please see them for review!

**Review by Joi — APPROVED** [review]
Great!

**Comment by yukis4san** [comment]
Yay!

**Pull request merged**
