### PR TITLE
structure change

### PR DESCRIPTION
**Pull request by yukis4san**
Separated sections in Japanese and English to improve information flow.
Deleted texts contents to be displayed in Discord channels since we are updating them (Discord.md).

### CODE REVIEW

**Comment by alecrem** [comment]
After this is merged, I will propose a nested structure on `SUMMARY.md` similar to this ["Simple example" on the GitBook docs](https://snowdreams1006.github.io/gitbook-official/en/pages.html).

But I don't understand why this PR is deleting most of the content on `discord.md`. If this has already agreed on, sorry for missing that. But @geeknees's #19 seems to be going in a different direction with the file.

**Comment by RyuKiyo66** [comment]
コメントだけで申し訳ありません。日本語だけ、以下の説明があります。それは良いとして、「オンボーディングのプロセス」という表現はなんとくなく理解できますが、不慣れな人には？？？のような気がしました。
- 下記のステップを実行して、HenkakuのDiscordに参加してください。
- オンボーディングのプロセスを円滑に実行するために、PCから下記の操作を行なってください（ChromeもしくはBraveを推奨しています）。

**Comment by geeknees** [comment]
I don't dislike the idea of deleting all the duplicate discord posts and gitbook content. Rather, my motto is "If you're worried about it, throw it away. 😃 

It may depend on whether @Joi needs to keep it as a reference to post Japanese posts.

In that case, I think the following two should be closed. I'm fine with that.
https://github.com/henkaku-center/henkaku-community/pull/19
https://github.com/henkaku-center/henkaku-community/pull/18

By the way, I don't know how much I should handle, but I can revert it later, so I'll go ahead with the merge until someone stops me.

**Comment by SamuraiT** [comment]
> Deleted texts contents to be displayed in Discord channels since we are updating them (Discord.md).

maybe good idea since discord channel will also change sometime.
so document updating/syncing costs could be minimal.

**Review by SamuraiT — CHANGES_REQUESTED** [review]
sorry mistake. lgtm

**Review by SamuraiT — APPROVED** [review]
lgtm

**Comment by alecrem** [comment]
lgtm

**Pull request merged**
